#!/usr/bin/env python3
"""Embed the resource portal assets into an Arduino header."""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PORTAL = ROOT / "nodo_recurso"
OUTPUT = PORTAL / "portal_assets.h"


def literal(name, delimiter, content):
    closing = ")" + delimiter + '"'
    if closing in content:
        raise ValueError("raw-string delimiter appears in " + name)
    return 'const char {}[] PROGMEM = R"{}({}){}";'.format(
        name, delimiter, content, delimiter
    )


def render():
    html = (PORTAL / "portal.html").read_text(encoding="utf-8")
    logic = (PORTAL / "portal_logic.js").read_text(encoding="utf-8")
    app = (PORTAL / "portal_app.js").read_text(encoding="utf-8")
    return "\n\n".join([
        "#pragma once",
        "// Generated by scripts/embed_nodo_recurso_portal.py. Do not edit by hand.",
        literal("RESOURCE_PORTAL_HTML", "WOKIHTML", html),
        literal("RESOURCE_PORTAL_LOGIC_JS", "WOKILOGIC", logic),
        literal("RESOURCE_PORTAL_APP_JS", "WOKIAPP", app),
    ]) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("portal_assets.h está desactualizado")
        return
    OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
